from .sahi_loan_agent import SAHI_LOAN_AGENT_INSTRUCTIONS
from .user_details_agent import USER_DETAILS_AGENT_INSTRUCTIONS
from .apply_for_new_loan_agent import APPLY_FOR_NEW_LOAN_AGENT_INSTRUCTIONS
from .apply_for_refinance_agent import APPLY_FOR_REFINANCE_AGENT_INSTRUCTIONS
from .general_query_agent import GENERAL_QUERY_AGENT_INSTRUCTIONS

__all__ = [
    "SAHI_LOAN_AGENT_INSTRUCTIONS",
    "USER_DETAILS_AGENT_INSTRUCTIONS",
    "APPLY_FOR_NEW_LOAN_AGENT_INSTRUCTIONS",
    "APPLY_FOR_REFINANCE_AGENT_INSTRUCTIONS",
    "GENERAL_QUERY_AGENT_INSTRUCTIONS"
]